### ISSUE TITLE
Fail to import module.

### ISSUE THREAD

**Issue by iMDeadalus** [ningxiaoxiao/comfyui-NDI#1]
hi, i am having trouble loading the NDI module. it fails to load cuz he can't find NDIlib. i have reinstall NDI tools and also updated the py folder to see if it helps but still fail to load just wondering if you can help me on how to load it. 

on startupb i get this.

  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI\__init__.py", line 13, in <module>
    import NDIlib as ndi
ModuleNotFoundError: No module named 'NDIlib'

Cannot import D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI module for custom nodes: No module named 'NDIlib

Thanks for the help in advance

**Comment by ningxiaoxiao** [comment]
pip install ndi-python

**Comment by iMDeadalus** [comment]
Thanks for the quick reply, still the same error for some reason. 

Just wondering would the problem be i am not running my comfy in the same drive could cause issue? since i am running my comfy on my SSD on D:\ and my NDI is installed in C:\users?

**Comment by ningxiaoxiao** [comment]
Maybe you are using an integrated version of comfyui, the root cause of this problem is that comfyui doesn't have the nid-python package in its python runtime environment. You just need to find a way to install this package in comfyui. If you are using the windows portable version, there should be a python_embedded.
E:\ComfyUI_windows_portable\python_embedded\Scripts\pip install ndi-python

**Comment by iMDeadalus** [comment]
Thanks for all the help, I couldn't get it to work on portable. So instead what I did is I installed new ComfyUI then made a venv to install all the python in. After that it seems to work, so for anyone else having a the same problem just have to follow this way to install your comfyui and it will work here is the link:

https://www.kombitz.com/2023/11/14/how-to-install-comfyui-on-windows-with-amd-gpu-using-pytorch-directml/

Thanks for the feedback Ningxiaoxiao.

**Comment by diogocondesantos** [comment]
Hey, In my case, I was missing the CV2 module to ndi node work. I use pinokio, I had to install opencv-python in the virtual env .

**Comment by davidrajadel** [comment]
Thank you for your comments. I am trying to install python-ndi since weeks without success. I work with comfyui on a secondary 'D' hard disk. I always get the same message no matter where I install it: venv, site-packages, both local and comfyui's own,... Am I missing something? i always get the same error

  0.0 seconds (IMPORT FAILED): D:\ConfyUI\ComfyUI_windows_portable\ComfyUI\Custom_nodes\comfyui-NDI


I have tried to install ndi-python in the possible paths like:

D:\ComfyUI_windows_portable\python_embedded\Lib\
D:\ComfyUI_windows_portable\python_embedded\Scripts
D:\ComfyUI_windows_portable\python_embedded\site-packages


C:\Users_ComfyUI\windows_portable\pypython\embedded\Lib\site-packages
C:\venv\Lib\site-packages
C:\venv\Scripts

Any solutions or steps I'm missing?

Thanks

**Comment by CalmClarity** [comment]
I have error does not  import , have followed instructions , can someone offer some advice and guidance thank you
 

### ComfyUI Revision: 2006 [18c151b3] | Released on '2024-02-20'
Loading ComfyUI-NDI nodes begin----------
Traceback (most recent call last):
  File "B:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "B:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI\__init__.py", line 13, in <module>
    import NDIlib as ndi
ModuleNotFoundError: No module named 'NDIlib'

Cannot import B:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI module for custom nodes: No module named 'NDIlib'

**Comment by ningxiaoxiao** [comment]
> Thanks for all the help, I couldn't get it to work on portable. So instead what I did is I installed new ComfyUI then made a venv to install all the python in. After that it seems to work, so for anyone else having a the same problem just have to follow this way to install your comfyui and it will work here is the link:
> 
> https://www.kombitz.com/2023/11/14/how-to-install-comfyui-on-windows-with-amd-gpu-using-pytorch-directml/
> 
> Thanks for the feedback Ningxiaoxiao.

**Comment by moebiussurfing** [comment]
There are similar problems here. 

```
PS D:\_AI> ComfyUI_windows_portable\python_embeded\python.exe -m pip install ndi-python
Collecting ndi-python
  Using cached ndi-python-5.1.1.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in d:\_ai\comfyui_windows_portable\python_embeded\lib\site-packages (from ndi-python) (1.26.2)
Building wheels for collected packages: ndi-python
  Building wheel for ndi-python (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\NDIlib
      copying NDIlib\__init__.py -> build\lib.win-amd64-cpython-311\NDIlib
      running build_ext
      cmake .. -DCMAKE_INSTALL_PREFIX=C:\Users\moebi\AppData\Local\Temp\pip-install-vxsj11nv\ndi-python_7537dd6145b94b57b2e10a57d6148d3d\build\install
      error: command 'cmake' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ndi-python
  Running setup.py clean for ndi-python
Failed to build ndi-python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ndi-python)
PS D:\_AI> ComfyUI_windows_portable\python_embeded\python.exe -m pip install cmake
Requirement already satisfied: cmake in d:\_ai\comfyui_windows_portable\python_embeded\lib\site-packages (3.30.2)
```

So, there's no way to install NDI and nodes when using the ComfyUI portable version?

**Comment by moebiussurfing** [comment]
Sorry, I forget to install cmake. 
Now I am getting:

```.bash
PS D:\_AI> ComfyUI_windows_portable\python_embeded\python.exe -m pip install ndi-python
Collecting ndi-python
  Using cached ndi-python-5.1.1.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in d:\_ai\comfyui_windows_portable\python_embeded\lib\site-packages (from ndi-python) (1.26.2)
Building wheels for collected packages: ndi-python
  Building wheel for ndi-python (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\NDIlib
      copying NDIlib\__init__.py -> build\lib.win-amd64-cpython-311\NDIlib
      running build_ext
      cmake .. -DCMAKE_INSTALL_PREFIX=C:\Users\moebi\AppData\Local\Temp\pip-install-x2_2h5ad\ndi-python_614c2b8a3a3a4755a5dc1dc497fd073f\build\install
      -- Building for: Visual Studio 17 2022
      -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.26120.
      -- The C compiler identification is MSVC 19.39.33523.0
      -- The CXX compiler identification is MSVC 19.39.33523.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:10 (add_subdirectory):
        add_subdirectory given source "lib/pybind11" which is not an existing
        directory.


      CMake Error at C:/Program Files/CMake/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
        Could NOT find NDI (missing: NDI_DIR FALSE)
      Call Stack (most recent call first):
        C:/Program Files/CMake/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
        cmake/Modules/FindNDI.cmake:45 (find_package_handle_standard_args)
        CMakeLists.txt:12 (find_package)


      -- Configuring incomplete, errors occurred!
      error: command 'C:\\Program Files\\CMake\\bin\\cmake.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ndi-python
  Running setup.py clean for ndi-python
Failed to build ndi-python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ndi-python)
```
