### ISSUE TITLE
(IMPORT FAILED): P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI

### ISSUE THREAD

**Issue by ShmuelRonen** [ningxiaoxiao/comfyui-NDI#2]
Hello...

I instaled everything include python-ndi and NDI screen capture
but got IMPORT FAILED on comfyui-NDI

File "P:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI\__init__.py", line 13, in <module>
    import NDIlib as ndi
ModuleNotFoundError: No module named 'NDIlib'

Cannot import P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI module for custom nodes: No module named 'NDIlib'

Can you help?

**Comment by drago87** [comment]
Having the same error and if i try to install the python-ndi module manually i get

```
D:\AI\ComfyUI_windows_portable\python_embeded>python.exe -m pip install -U ndi-python
Collecting ndi-python
  Using cached ndi-python-5.1.1.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in d:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from ndi-python) (1.24.4)
Building wheels for collected packages: ndi-python
  Building wheel for ndi-python (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\NDIlib
      copying NDIlib\__init__.py -> build\lib.win-amd64-cpython-311\NDIlib
      running build_ext
      cmake .. -DCMAKE_INSTALL_PREFIX=C:\Users\Drago87\AppData\Local\Temp\pip-install-_objz295\ndi-python_8c68929969ab4d5d9bc16e02d316373e\build\install
      -- Building for: Visual Studio 16 2019
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
      -- The C compiler identification is MSVC 19.29.30152.0
      -- The CXX compiler identification is MSVC 19.29.30152.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:10 (add_subdirectory):
        add_subdirectory given source "lib/pybind11" which is not an existing
        directory.


      -- Found NDI: D:/Program/NDI/NDI 5 SDK
      CMake Error at CMakeLists.txt:19 (pybind11_add_module):
        Unknown CMake command "pybind11_add_module".


      -- Configuring incomplete, errors occurred!
      error: command 'C:\\Users\\Drago87\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\cmake.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ndi-python
  Running setup.py clean for ndi-python
Failed to build ndi-python
ERROR: Could not build wheels for ndi-python, which is required to install pyproject.toml-based projects
```

somehow it is trying to use a installed 3.10 version of python `C:\\Users\\Drago87\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\cmake.exe`

**Comment by Sportinger** [comment]
same thing.

**Comment by Xenodimensional** [comment]
Me three

**Comment by Xenodimensional** [comment]
zzz

**Comment by M4R5W0N6** [comment]
bump

**Comment by ningxiaoxiao** [comment]
my python version is 3.10.9
u can try this:
P:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install ndi-python

**Comment by ningxiaoxiao** [comment]
Because I am using the `ndi-python` library, there are already related solutions in its issues, which can be referenced: 
https://github.com/buresu/ndi-python/issues/31#issue-1712585187

**Comment by M4R5W0N6** [comment]
followed those instructions:

`Loading ComfyUI-NDI nodes begin----------
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI\__init__.py", line 13, in <module>
    import NDIlib as ndi
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\NDIlib\__init__.py", line 7, in <module>
    from .NDIlib import *
ModuleNotFoundError: No module named 'NDIlib.NDIlib'`

upon moving __init__.py up a level, or changing ".NDIlib" to "." :

`Loading ComfyUI-NDI nodes begin----------
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI\__init__.py", line 17, in <module>
    ndi_find=ndi.find_create_v2()
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'NDIlib' has no attribute 'find_create_v2'`

**Comment by M4R5W0N6** [comment]
also, not sure why your python-embedded is 3.10.9 -- i've recently updated ComfyUI and mine reads:

`PS D:\Github\ndi-python> C:\ComfyUI_windows_portable\python_embeded\python.exe
Python 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.`

**Comment by ningxiaoxiao** [comment]
[requirements.txt](https://github.com/ningxiaoxiao/comfyui-NDI/files/14580901/requirements.txt)
this is my python_embeded lib list
I also don't know why my Python is at 3.10.9. Maybe I haven't updated it.
