### ISSUE TITLE
NDI plug in

### ISSUE THREAD

**Issue by 55878** [ningxiaoxiao/comfyui-NDI#4]
I am currently trying to install ndi-python and getting a series of errors and if possible could you connect with me to fix these errors. 

thank you for your time 

Joe.

**Comment by sebbean** [comment]
what errors

**Comment by 55878** [comment]
NDI is not installing correctly as the error is

(
#"C:\Windows\System32>pip install ndi-python Defaulting to user
installation because normal site-packages is not writeable Collecting
ndi-python Using cached ndi-python-5.1.1.1.tar.gz (16 kB) Installing build
dependencies ... done Getting requirements to build wheel ... done
Installing backend dependencies ... done Preparing metadata
(pyproject.toml) ... done Requirement already satisfied: numpy in
c:\users\sleep\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages
(from ndi-python) (1.26.4) Building wheels for collected packages:
ndi-python Building wheel for ndi-python (pyproject.toml) ... error error:
subprocess-exited-with-error × Building wheel for ndi-python
(pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [35 lines of
output] running bdist_wheel running build running build_py creating build
creating build\lib.win-amd64-cpython-312 creating
build\lib.win-amd64-cpython-312\NDIlib copying NDIlib\__init__.py ->
build\lib.win-amd64-cpython-312\NDIlib running build_ext cmake ..
-DCMAKE_INSTALL_PREFIX=C:\Users\sleep\AppData\Local\Temp\pip-install-fc28s8fr\ndi-python_2d0d3abe0ffc47b1b08df7566d3c8450\build\install
-- Building for: Visual Studio 17 2022 -- Selecting Windows SDK version
10.0.22621.0 to target Windows 10.0.22631. -- The C compiler identification
is MSVC 19.39.33523.0 -- The CXX compiler identification is MSVC
19.39.33523.0 -- Detecting C compiler ABI info -- Detecting C compiler ABI
info - done -- Check for working C compiler: C:/Program Files/Microsoft
Visual
Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe -
skipped -- Detecting C compile features -- Detecting C compile features -
done -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info
- done -- Check for working CXX compiler: C:/Program Files/Microsoft Visual
Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe -
skipped -- Detecting CXX compile features -- Detecting CXX compile features
- done CMake Error at CMakeLists.txt:10 (add_subdirectory):
add_subdirectory given source "lib/pybind11" which is not an existing
directory. -- Found NDI: C:/Program Files/NDI/NDI 5 SDK CMake Error at
CMakeLists.txt:19 (pybind11_add_module): Unknown CMake command
"pybind11_add_module". -- Configuring incomplete, errors occurred! error:
command 'C:\\Program Files\\CMake\\bin\\cmake.exe' failed with exit code 1
[end of output] note: This error originates from a subprocess, and is
likely not a problem with pip. ERROR: Failed building wheel for ndi-python
Failed to build ndi-python ERROR: Could not build wheels for ndi-python,
which is required to install pyproject.toml-based projects)



[image: "created with MySignature.io"]
<https://mysignature.io/?utm_source=logo>
Joseph James Barilla
Media server Operator, Laser Designer Endless productions
w: vjchatgpt.myportfolio.com <https://mysig.io/7oaq056o>
e: ***@***.***
p:  (702) 817 9470 <+(702)+817+9470>
[image: created with MySignature.io] <https://mysig.io/xraMklPr> [image:
created with MySignature.io] <https://mysig.io/9vaMK84v>
[image: created with MySignature.io]
<https://mysignature.io/editor?utm_source=freepixel>

**Comment by sebbean** [comment]
this is where' i'm at rn:
https://github.com/buresu/ndi-python/issues/34#issuecomment-1882125301

**Comment by ningxiaoxiao** [comment]
It seems that the above response has already solved this issue, so I want to close this issue. Thanks sebbean
https://github.com/buresu/ndi-python/issues/34#issuecomment-1882125301
